### ISSUE TITLE
Suggestion: More breach sources

### ISSUE THREAD

**Issue by 7ez75** [thesaderror/vector#4]
This is not a bug, just a suggestion.

So, I tried searching using email, the results are as shown below. It seems to indicate that there are no results.

!["img1"](https://a.pomf.cat/mwbclb.png)

I checked in HIBP using the same email, there were results.

!["img2"](https://a.pomf.cat/kkbhkp.png)

I checked the source code, it breach search uses the leakcheck API. So why the info doesn't appear, maybe because of the limitations of leakcheck.

My suggestion, in the future it will better if many breach sources are used.

**Comment by theahmadov** [comment]
Yes. Thanks friend. Leakcheck is weird. We will add haveibeenpwned api. Thanks for issue. We will close it when we solve problem. If you can you should create pull request.

**Comment by theahmadov** [comment]
> This is not a bug, just a suggestion.
> 
> So, I tried searching using email, the results are as shown below. It seems to indicate that there are no results.
> 
> !["img1"](https://camo.githubusercontent.com/028c4230e5cdaad4b79e3145cc9aac79d92dfa00786113ac31126234392c60c7/68747470733a2f2f612e706f6d662e6361742f6d7762636c622e706e67)
> 
> I checked in HIBP using the same email, there were results.
> 
> !["img2"](https://camo.githubusercontent.com/a416b1183e1c656cccf8f8b0153ec752a71d3f5cfd12013a1aa0b01252eb582b/68747470733a2f2f612e706f6d662e6361742f6b6b62686b702e706e67)
> 
> I checked the source code, it breach search uses the leakcheck API. So why the info doesn't appear, maybe because of the limitations of leakcheck.
> 
> My suggestion, in the future it will better if many breach sources are used.

Yo I tried hibw but it dont show exactly right. Like when I input email adress in hibw it show nothing. But when I use vector's it show its pwned. Like stealer logs....
